# this is a licence application demo. 
# this file includes "drug-search". to test it, rename it to "docker-compose.yml" 
# drug-search url: http://localhost:4600
# licence-applicaiton-web url: http://localhost:4500
version: "2"
services:
  licence-web:
    container_name: licence-web
    image: weifang993/licence-application-web
    restart: always
    ports:
      - "4500:80"
  drug-search:
    container_name: drug-search
    image: weifang993/drug-search
    restart: always
    ports:
      - "4600:80"
  dpd-service:
    container_name: dpd-service
    image: weifang993/dpd-server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
  licence-service:
    container_name: licence-service
    image: weifang993/licence-application-server
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "27017:27017"
