# this is a licence application demo. 
version: "2"
services:
  licence-web:
    container_name: licence-web
    image: weifang993/licence-application-web
    restart: always
    ports:
      - "4500:80"
  dpd-service:
    container_name: dpd-service
    image: weifang993/dpd-server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
  licence-service:
    container_name: licence-service
    image: weifang993/licence-application-server
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: qqzhangl/mongo
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "27017:27017"
