# this is a drug search demo. 
# to run it, `[sudo ] docker-compose -f dpd.yml up" 
# drug-search url: http://localhost:4600
version: "3"
services:
  drug-search:
    container_name: drug-search
    image: weifang993/drug-search
    restart: always
    ports:
      - "4600:8080"
  dpd-service:
    container_name: dpd-service
    image: weifang993/dpd-server
    restart: always
    ports:
      - "8080:8080"
  # dpd-service:
  #   container_name: dpd-node-service
  #   image: weifang993/dpd-node-server
  #   restart: always
  #   ports:
  #     - "8080:3000"
  #   environment:
  #     - MONGODB_SERVICE_HOST=localhost
  #     - MONGODB_SERVICE_PORT=27017    
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "27017:27017"
