# this is a licence application demo. 
# this file includes "drug-search". to test it, rename it to "docker-compose.yml" 
# drug-search url: http://localhost:4600
# licence-applicaiton-web url: http://localhost:4500
version: "3"
services:
  drug-search:
    container_name: drug-search
    image: weifang993/drug-search
    restart: always
    ports:
      - "4600:8080"
  dpd-service:
    container_name: dpd-service
    image: weifang993/dpd-node-server
    restart: always
    environment:
      - MONGODB_SERVICE_HOST=127.0.0.1
      - MONGODB_SERVICE_PORT=27017
    ports:
      - "8080:3000"
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "27017:27017"
