# this is a drug search demo. 
# to run it, `[sudo ] docker-compose -f dpd.yml up" 
# drug-search url: http://localhost:4600
version: "3"
services:
  drug-search:
    container_name: drug-search
    image: weifang993/drug-search
    restart: always
    ports:
      - "4600:8080"
    depends_on:
      - dpd-service  
  dpd-service:
    container_name: dpd-node-service
    image: weifang993/dpd-node-server
    restart: always
    ports:
      - "8080:3000"
    environment:
      - MONGODB_SERVICE_HOST=mongo
      - MONGODB_SERVICE_PORT=27017    
    depends_on:
      - mongo  
  mongo:
    container_name: mongo
    image: qqzhangl/mongo
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "27017:27017"
